### ISSUE TITLE
need to store task in user's phone

### ISSUE THREAD

**Issue by AshAman999** [AshAman999/ToDo-app-flutter#1]
#1
need to find a way to store the data into user's local storage so that the state or the tasks created is not lost when exiting the app.

**Comment by Akshay0701** [comment]
i will try to do that

**Comment by AshAman999** [comment]
@Akshay0701  yeah sure, go ahead

**Comment by AshAman999** [comment]
@Akshay0701 
 i hope you would have worked it out😕?
